name: example
description: A example of essential_xlsx library

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1  
  angular_router: ^2.0.0-alpha+21
  angular_forms: ^2.1.4  
  essential_xlsx:
    path: ../

dev_dependencies:  
  angular_test: any
  build_runner: ^1.7.3
  build_test: ^0.10.12
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0
  test: any
  sass_builder: ^2.1.2